//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mgmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wh_list()
        {
            this.wh_dep = new HashSet<wh_dep>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string id_user { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wh_dep> wh_dep { get; set; }
    }
}
